// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Domain.Entities.ProductionWorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("Infrastructure.DLQ.DeadLetterRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FailedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeadLetters");
                });

            modelBuilder.Entity("Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Value");

                    b.ToTable("IdempotencyRecords");
                });

            modelBuilder.Entity("Domain.Entities.ProductionWorkOrder", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.IdempotencyKey", "IdemKey", b1 =>
                        {
                            b1.Property<Guid>("ProductionWorkOrderId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Value")
                                .HasColumnType("TEXT");

                            b1.HasKey("ProductionWorkOrderId");

                            b1.ToTable("WorkOrders");

                            b1.WithOwner()
                                .HasForeignKey("ProductionWorkOrderId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Payload", "Payload", b1 =>
                        {
                            b1.Property<Guid>("ProductionWorkOrderId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("TEXT");

                            b1.HasKey("ProductionWorkOrderId");

                            b1.ToTable("WorkOrders");

                            b1.WithOwner()
                                .HasForeignKey("ProductionWorkOrderId");
                        });

                    b.Navigation("IdemKey");

                    b.Navigation("Payload");
                });
#pragma warning restore 612, 618
        }
    }
}
